#!/bin/sh

set -e

# Only retain data for `DATA_RETENTION_DAYS` days
# This is a workaround that allows usage of upstream image
sed -i -r "s/days_to_retain=7/days_to_retain=${DATA_RETENTION_DAYS:-7}/" /usr/local/lib/python2.7/site-packages/cabot/cabotapp/tasks.py

# Run cabot with all services in a single container
gunicorn cabot.wsgi:application -b 0.0.0.0:$PORT &
celery worker -A cabot &
celery beat -A cabot &

echo "Cabot container booted!"
wait
